# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_LOG_BACKEND_RTT=y

# Console / stdout
CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=n     # IMPORTANT: do NOT bind console to a UART
CONFIG_STDOUT_CONSOLE=y

# Serial API: leave disabled to avoid the console claiming UART device
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

# Suppress mbedTLS RNG warnings (harmless in this app)
CONFIG_MBEDTLS_PSA_CRYPTO_EXTERNAL_RNG=n
CONFIG_MAIN_STACK_SIZE=4096

CONFIG_UART_ASYNC_API=y
CONFIG_UART_NRFX=y
CONFIG_LOG_PROCESS_THREAD=y        # enables non-blocking LOG_INF
CONFIG_LOG_MODE_IMMEDIATE=n        # use deferred mode (safe in ISR/callback)
CONFIG_UART_LOG_LEVEL_DBG=y

CONFIG_LOG_BUFFER_SIZE=2048
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=1024

